---
# handlers file for setup-apache
- name: start apache
  service:
    name: httpd
    state: started

- name: start apache2
  service:
    name: apache2
    state: started

      # - name: start firewalld
      # service:
      # name: firewalld
      # state: started
      # enabled: true

      # - name: permit http service
      # firewalld:
      # service: http
      # permanent: true
      # state: enabled
      # immediate: yes

- name: restart apache
  service:
    name: httpd
    state: restarted

- name: restart apache2
  service:
    name: apache2
    state: restarted
