---
- name: Ansible playbook to test ansible vault
  hosts: all
  become: true
  vars_files:
    - vault-pass.yml
  tasks:
    - name: clone repo
      git:
        repo: https://yankils:{{ password }}@github.com/yankils/vault.git
        dest: /opt/ansadmin/test-vault
